### ISSUE TITLE
Taskbar icons jump randomly from left to middle

### ISSUE THREAD

**Issue by ion-elgreco** [ChrisAnd1998/TaskbarX#285] opened 2020-05-12 13:36 UTC
Store or Regular version: Store version
What's your Build of Windows 10: Build 18362.19h1_release.190318-1202
.NET Framework 4.8 installed: Yes
Any Antivirus software: No
Any other third-party taskbar tweakers: No
Is there a way i can reproduce: No
What are your taskbar settings: Only speed change to 100ms
What says the error message if you got any: No error message

The taskbar randomly jumps from middle to the left and back to middle. The previous version this way worse, but in 15.5.0 it still does it occasionally.

**Comment by VlaDosWOW** [comment] 2020-05-13 09:47
I have same issue when task manager opening on Ctrl+Shift+Esc, but I made temporary solution.
Bat script that restarting TaskbarX, before running it you need to add folder where TaskbarX placed,
E.g `C:\Program Files\TaskbarX\` to environment variable Path https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

I advice use shrortcut and pin it to toolbar on taskbar
![image](https://user-images.githubusercontent.com/49435083/81796465-232a1100-9516-11ea-80aa-4563851f7bf1.png)
https://answers.microsoft.com/en-us/windows/forum/windows_10-start-win_taskbar/add-quick-launch-toolbar-to-taskbar-in-windows-10/7c365da5-1d58-4c0f-bffe-afa1d3af006d?auth=1

Script and shortcut: [restartTaskX.zip](https://github.com/ChrisAnd1998/TaskbarX/files/4621039/restartTaskX.zip)

**Comment by VlaDosWOW** [comment] 2020-05-13 10:04
I have same issue when task manager opening on Ctrl+Shift+Esc, but I made temporary solution.
Bat script that restarting TaskbarX, before running it you need to add folder where TaskbarX placed,
E.g `C:\Program Files\TaskbarX\` to environment variable Path https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

I advice use shrortcut and pin it to toolbar on taskbar
![image](https://user-images.githubusercontent.com/49435083/81798797-1c50cd80-9519-11ea-92d2-8315084a428c.png)
https://answers.microsoft.com/en-us/windows/forum/windows_10-start-win_taskbar/add-quick-launch-toolbar-to-taskbar-in-windows-10/7c365da5-1d58-4c0f-bffe-afa1d3af006d

Script and shortcut: [restartTaskX.zip](https://github.com/ChrisAnd1998/TaskbarX/files/4621217/restartTaskX.zip)

**Comment by SnailMango** [comment] 2020-05-14 10:49
I have the same issue when opening/closing apps. Issue mainly occurs with fullscreen apps like when closing or alt-tabbing games.

**Comment by VlaDosWOW** [comment] 2020-05-15 13:35
Best way to fix this issue is download old version of FalconX, and wait.
https://howdyho.net/windows-software/falconx-znachki-po-centru-v-paneli-zadach?download

**Comment by SnailMango** [comment] 2020-05-15 14:57
> Best way to fix this issue is download old version of FalconX, and wait.
> https://howdyho.net/windows-software/falconx-znachki-po-centru-v-paneli-zadach?download

I thought it didn't work anymore. Is it still working even if it can't reach the server for updates?
FalconX was working very well before installing TaskbarX.

**Comment by ChrisAnd1998** [comment] 2020-05-18 05:22
My apologies for the late response.
Trying my best to make TaskbarX work for everyone. FalconX was hardcoded and so limited to max 3 monitors. TaskbarX gets all information automatically and needs more fine tuning but, supports unlimited monitors and settings.

TaskbarX restarts on the general settings change even. This works fine for most people but, clearly results in unnecessary restarts in some occasions. I am thinking of removing that event but, will require you to manually restart TaskbarX using the configurator if you make drastic changes to the taskbar. In some cases it will just adjust itself.

Old builds can be downloaded from here:
http://chrisandriessen.nl/downloads/taskbarx/

**Comment by didpoy** [comment] 2020-05-18 12:42
Hello,

Same problem with version 1.5.6.0. the icons go to the right with the task manager.

But the FalconX 1.4.5.0 software works perfectly !!!!

Please make a correction to this excellent tool.

Cordially.

**Comment by ion-elgreco** [comment] 2020-05-18 16:26
> Hello,
> 
> Same problem with version 1.5.6.0. the icons go to the right with the task manager.
> 
> But the FalconX 1.4.5.0 software works perfectly !!!!
> 
> Please make a correction to this excellent tool.
> 
> Cordially.

I reverted back to 1.4.5.0. It seems to have fixed all of the issues. It now stops bouncing from left to right constantly. If I change to my second virtual desktop, it will bounce back to the middle as it should.

@ChrisAnd1998 Maybe in the process of re-working the whole sourcecode, something went wrong, because 1.4.5.0 is very stable!

**Comment by ChrisAnd1998** [comment] 2020-05-18 17:12
@ion-elgreco And 1.5.6.0 pre-release from today doesn't fix it?
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.6.0

There also is a Monitor Changed event. I don't know if this also triggers when using virtual desktops... i will test this.

@didpoy mentioned it going to the right which maybe another issue.

**Comment by ion-elgreco** [comment] 2020-05-18 17:17
> @ion-elgreco And 1.5.6.0 pre-release from today doesn't fix it?
> https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.6.0
> 
> There also is a Monitor Changed event. I don't know if this also triggers when using virtual desktops... i will test this.
> 
> @didpoy mentioned it going to the right which maybe another issue.

I'll try it out tonight, it's working fine now, so I am not hesitant to switch haha

**Comment by didpoy** [comment] 2020-05-21 10:09
Hello,

the 1.5.6.0 does not solve the problem of the icons which hangs completely on the right, or even disappear, when opening the task manager among others ...

Thank you.

**Comment by VlaDosWOW** [comment] 2020-05-21 11:44
I removed takbar toolbar
Before:
![Inked81798797-1c50cd80-9519-11ea-92d2-8315084a428c_LI](https://user-images.githubusercontent.com/49435083/82555315-3705f080-9b70-11ea-8553-d653c36465a7.jpg)
After:
![image](https://user-images.githubusercontent.com/49435083/82555395-5b61cd00-9b70-11ea-8049-b08495c49166.png)

Taskbar stoped jumping to middle.

**Comment by didpoy** [comment] 2020-05-21 12:17
Yes, it is a solution, but I would like to keep my taskbar toolbar since version 1.4.5.0 (falconX) works well with this additional bar!

**Comment by ChrisAnd1998** [comment] 2020-05-23 13:01
Allright, can somebody give 1.5.7.0 a try? With the toolbar enabled on the left
![](https://user-images.githubusercontent.com/49435083/82555315-3705f080-9b70-11ea-8553-d653c36465a7.jpg)

https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.7.0

**Comment by ion-elgreco** [comment] 2020-05-23 13:07
> Allright, can somebody give 1.5.7.0 a try? With the toolbar enabled on the left
> ![](https://user-images.githubusercontent.com/49435083/82555315-3705f080-9b70-11ea-8553-d653c36465a7.jpg)
> 
> https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.7.0

Im running 1.5.7.0 now. It centers again after switching between virtual desktops now. Ill let's you know if it bounces from left to right sometimes.

**Comment by ChrisAnd1998** [comment] 2020-05-23 13:12
Allright, thanks for the quick reply :)

**Comment by ion-elgreco** [comment] 2020-05-23 13:14
> @ion-elgreco Allright, thanks for the quick reply :)

I am having some other issues though, from eventviewer:

Application: TaskbarX Configurator.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Diagnostics.Process.StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo)
   at TaskbarXConfiguratorWPF.MainWindow.RevertToZero()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Faulting application name: TaskbarX Configurator.exe, version: 1.5.7.0, time stamp: 0xdebdece3
Faulting module name: KERNELBASE.dll, version: 10.0.18362.815, time stamp: 0x67005c2a
Exception code: 0xe0434352
Fault offset: 0x00114402
Faulting process ID: 0x1444
Faulting application start time: 0x01d63103a12813b5
Faulting application path: C:\Users\ion\Downloads\Release\TaskbarX Configurator.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 6d6c68c4-574a-4e26-ab66-f5106d5b6a18
Faulting package full name: 
Faulting package-relative application ID:

**Comment by ChrisAnd1998** [comment] 2020-05-23 13:18
@ion-elgreco Hmm, don't really know why that happens... It happend when starting TaskbarX through the configurator.

**Comment by ion-elgreco** [comment] 2020-05-23 13:26
> @ion-elgreco Hmm, don't really know why that happens... It happend when starting TaskbarX through the configurator.

Figured it out ;) If I change the schedule time, and apply it. Then taskbarx crashes, restarting won't work. Restarting from configuratorx won't work. Taskbar will lose it's blur and the icons will remain in the middle. 

Only way to fix it is with a restart.

**Comment by ion-elgreco** [comment] 2020-05-23 13:32
Disabling update taskbar toolbars crashes taskbar, but it won't save that setting. Only a restart of windows fixes it.

**Comment by ChrisAnd1998** [comment] 2020-05-23 13:44
Damn, your'e experiencing so many issues i can't even reproduce them XD.
It's all working fine without the custom toolbar?

**Comment by ion-elgreco** [comment] 2020-05-23 14:02
> Damn, your'e experiencing so many issues i can't even reproduce them XD.

At least the taskbar icons don't jump from left to right and the virtual desktop switching works ;) But adjusting settings results in crash haha

**Comment by didpoy** [comment] 2020-05-23 15:11
For me version 1.5.7.0 works well. Everything stays centered on the first desktop (not tried on others), even using the task manager.
No crashes ...
Update TaskBar toolbars remains continuously checked even after having unchecked it and applied!
I don't see many differences between the various animations where they are subtle.

**Comment by ChrisAnd1998** [comment] 2020-05-23 16:45
@didpoy 

> Update TaskBar toolbars remains continuously checked even after having unchecked it and applied!

Should be fixed now ;)

**Comment by didpoy** [comment] 2020-05-25 09:06
I tested it under Windows 8.1 and here are the errors encountered at the base:

Installation:
The program cannot be started because api-ms-win-crt-string-l1-1-0.dll is missing from your computer. Try reinstalling the program to correct this problem.

At Launch:
@ Looper2 | Unable to load DLL 'oleacc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Closed** 2020-09-12 10:21 UTC

**Comment by rbreaves** [comment] 2021-07-05 17:59
Looks like this issue has returned under the latest 1.7.x release. I've simply removed it for now. It ends up just opening and re-opening the app over and over. I do log into multiple user accounts on this computer so I am not sure if they issue is related to that any or not.
