### ISSUE TITLE
Icons scrolling out of the screen

### ISSUE THREAD

**Issue by AnonM00se** [ChrisAnd1998/TaskbarX#553] opened 2021-02-06 11:16 UTC
**Describe the bug**
The icons on taskbar move towards the right until they can no longer be seen.

**To Reproduce**
1. Run TaskbarX
2. Icons start moving towards the right infinitely

**Expected behavior**
the icons should be centered

**Screenshots**
![103908918-13a4ab80-5129-11eb-8866-c5456c593767](https://user-images.githubusercontent.com/60802461/107116631-9e570280-68af-11eb-83ba-139abf6a5273.png)
took the screenshot above from another post because we have the same problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 1909

**Comment by Zedboy** [comment] 2021-02-08 01:25
That happened to me, too

**Comment by Mavavaron** [comment] 2021-02-17 12:15
The same thing happened to me, I have Windows 10 Pro, Version: 20H2

**Comment by Rumia** [comment] 2021-02-21 21:26
Same here. This issue has been present since 1.5.5.0 :/

- Single Monitor
- Version 2004

**Comment by ChrisAnd1998** [comment] 2021-03-21 07:43
Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

**Comment by plasticgiskard** [comment] 2021-03-21 07:59
> Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

Works great, the iconst no longer scroll off the screen. The icons were aligned to the right by default, but you can center them by adjusting the primary taskbar offset (the magic number for me was -250 px on a 15" laptop screen with a resolution of 1920/1080). 

Thank you for posting this update, much appreciated.

**Comment by ChrisAnd1998** [comment] 2021-03-25 07:10
I have made some improvements to the calculations from what didn't work on your end. As you explained the last pre-release works. Like older versions of FalconX and TaskbarX it counts each button's width. The problem is that other bugs came along with this fix that I'm really struggling on to fix. So I tried improving what didn't work on your end (Calculating the position from the first icon position to the last.). 

Can you try the **ReleaseV4.zip** on https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0 ?

When I dropped the refresh rate to 100ms it was easy to make it bug out (moving in different directions randomly). After the fix in V4 I'm not able to make it bug out anymore which is the same behaviour as the first test you are running at the moment. I even managed to improve it's performance (Even less CPU usage).

**Comment by Rumia** [comment] 2021-03-25 10:20
I have the same issue that plasticgiskard mentioned, and v4 didn't fix it. 
![2021-03-25_11-14-56](https://user-images.githubusercontent.com/8923393/112456950-8a7e3780-8d5b-11eb-9dd3-76c972b65da9.png)

The other thing I've noticed is that the taskbar doesn't update/re-center after opening and closing a lot of apps.

**Comment by ChrisAnd1998** [comment] 2021-03-25 11:22
@Rumia Can you open this application **UISpy.exe**
[UISpy.zip](https://github.com/ChrisAnd1998/TaskbarX/files/6204121/UISpy.zip)

Find the taskbar like in my screenshot and highlight the last blank item.
Then create a screenshot so I can see it's info. Maybe this tells me more.

![Untitled](https://user-images.githubusercontent.com/50437199/112465174-b0f4a080-8d64-11eb-9a1f-62e22ab30022.png)

**Comment by Rumia** [comment] 2021-03-25 12:18
![UISpy_2021-03-25_13-12-17](https://user-images.githubusercontent.com/8923393/112471248-eea8f780-8d6b-11eb-8777-b9e068021745.png)

**Comment by ChrisAnd1998** [comment] 2021-03-25 14:57
@Rumia Something weird is going on in your structure. I see you expanded the Rebar but then you have _Ausgefuhrte Anwendungen_ "Running Applications" without an option to expand the list with buttons. Like in my screenshot. When i look at your screenshot i can see the taskbar is positioned on 0 from the center. So TaskbarX is not even reading any icons in your taskbar.

Can you hit the File > Save Snapshot from Root... and give me that XML so i can dig into your structure? Maybe they have a different location than normal.
![Untitle22d](https://user-images.githubusercontent.com/50437199/112493725-b5c84d00-8d82-11eb-8faa-53c66707d32c.png)

**Comment by Rumia** [comment] 2021-03-25 16:08
Sorry, took me a while to get a working snapshot 
[snapshot.zip](https://github.com/ChrisAnd1998/TaskbarX/files/6206158/snapshot.zip)

**Comment by ChrisAnd1998** [comment] 2021-03-25 18:23
No problem ;) I have taken a look at your snapshot but they are just not listed.. Something is wrong with MSAA. And the error confirms that. https://en.wikipedia.org/wiki/Microsoft_Active_Accessibility

I'll take a look at that error maybe I can find something about this.

**Comment by Rumia** [comment] 2021-03-25 18:49
I think I've managed to fix it. Everything is working so far, the taskbar updates properly, and it's centered.

[https://docs.uipath.com/studio/docs/identifying-ui-elements-after-windows-updates](url)

I followed the steps within this article to re-register the oleacc.dll and fix some registry entries.

**Comment by ChrisAnd1998** [comment] 2021-03-25 19:24
Great!!! This is interesting..

**Comment by Rumia** [comment] 2021-03-25 20:06
Yeah. Might be a broken windows update.. I don't know :/ 
Anyways.. Thank you for taking the time to help me! Let me know if you need anything else. :)

**Comment by ChrisAnd1998** [comment] 2021-03-25 20:32
Allright 😁👍

**Comment by ChrisAnd1998** [comment] 2021-12-25 10:47
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️

**Closed by ChrisAnd1998** 2021-12-25 10:47 UTC
Labels: Issue Priority: Low, Working on it
