### ISSUE TITLE
Combine Taskbar buttons while hiding labels.

### ISSUE THREAD

**Issue by Aktimoose** [ChrisAnd1998/TaskbarX#669] opened 2021-06-13 18:30 UTC
**Describe the solution you'd like**
A way to not combine taskbar buttons while still hiding labels, which appears to not already be a feature in Windows.
![image](https://user-images.githubusercontent.com/44620677/121818215-b4216d80-cc7d-11eb-9d20-cd77b04f85a0.png)

**Describe alternatives you've considered**
I've attempted using regedits to change the width of taskbar buttons to hide the text while grouping is on, to no avail. However, even if this had worked, it's clunky and would be hard to undo, so being able to easily change it with TaskbarX would be preferred anyways.

**Additional context**
![image](https://user-images.githubusercontent.com/44620677/121818193-9ce28000-cc7d-11eb-8d8a-d6dad5c9efb6.png)

**Comment by Blaconix** [comment] 2021-06-19 18:47
Duplicate of https://github.com/ChrisAnd1998/TaskbarX/issues/124

**Comment by ChrisAnd1998** [comment] 2021-12-25 11:00
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️

**Closed by ChrisAnd1998** 2021-12-25 11:00 UTC
