### ISSUE TITLE
Windows 11 22H2 screen not supported

### ISSUE THREAD

**Issue by monster3037** [ChrisAnd1998/TaskbarX#1006] opened 2022-09-29 13:24 UTC
After Upgrading to windows 11, taskbarx is not working,  please rectify it or either refund my money

**Comment by api-was-taken** [comment] 2022-09-30 21:01
same

**Comment by NobiteK** [comment] 2022-10-02 14:21
same

**Comment by ChrisAnd1998** [comment] 2022-10-03 05:34
I will close this issue as it is a duplicate of #1004

**Closed by ChrisAnd1998** 2022-10-03 05:34 UTC
