### ISSUE TITLE
Can We Find A Solution To This

### ISSUE THREAD

**Issue by AboBelal2999** [ChrisAnd1998/TaskbarX#321] opened 2020-07-14 15:39 UTC
My Win Ver 2004
Pc Display Language Arabic
https://youtu.be/zBsAqQDTMUY
@ChrisAnd1998

**Comment by Rahsna** [comment] 2020-07-18 12:09
To clarify for those checking of already reportet bugs before posting a new one:
"This" is the taskbar icons' move animation unexpectantly repeating several times when changing position properties and transition method.

**Comment by ChrisAnd1998** [comment] 2021-03-21 10:34
Can you try this? https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.8.0

**Comment by Rahsna** [comment] 2021-03-22 08:17
It seems to be fixed with release 1.6.8.0 🙂
I tried to reproduce the actions seen in the video. The behaviour in the video was no longer reproduceable 👍🏼

ℹI noticed that the video-person's language is a right to left-language, so that _might_ also be a factor.
I did not reproduce that part of the testing environment, so keep that in mind.

**Comment by ChrisAnd1998** [comment] 2021-03-22 08:47
@Rahsna Thanks for letting me know! 👍 Right to left doesn't really work well though. There are some little issues that came along with the fix so the full release can take some time.

**Comment by Rahsna** [comment] 2021-03-25 14:22
You're welcome!
Thank you for letting us know the expected update will be taking longer than usual, happy coding and thank you for improving the app 🙂

**Comment by ChrisAnd1998** [comment] 2021-12-25 10:39
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️

**Closed by ChrisAnd1998** 2021-12-25 10:39 UTC
Labels: Issue Priority: Low
