### ISSUE TITLE
Version 1.7.2.0 does not center the taskbar

### ISSUE THREAD

**Issue by Xampersand** [ChrisAnd1998/TaskbarX#787] opened 2021-08-29 13:46 UTC
"Waiting for Shell_TrayWnd
@Calculator | Object reference not set to an instance of an object."

this is what I get in the CMD that pops up and even if i mess around with settings, restart, reapply, reinstall it never centers the taskbar.

**Comment by j3rseyhack** [comment] 2021-08-29 19:06
Having the same problem now. Just did a new PC and will not center either.

**Comment by nullpenguinexception** [comment] 2021-08-31 06:39
This man kidding with us, this cannot be explained with another way. There are plenty of issue about taskbarx's centering problem. Instead of fixing that critical issue, he's just upgrading dependencies version. Use TranslucentTB, it's way better and their developers are really interested.

**Comment by christubuntu** [comment] 2021-08-31 09:39
It's not only that version. all 1.7.xxx versions don't work for me. Had to revert to 1.6.9.0

**Comment by ErNabba** [comment] 2021-09-01 07:52
I have exactly the same problem also with the main monitor, the strange thing is that the secondary monitor works well. I'm relieved not to be the only one with this problem.

**Comment by LeCyreaxYT** [comment] 2021-09-01 19:38
#783 there is a PR with a fix but yes the 1.6.9.0 has no Problems ^^

**Comment by lakayte** [comment] 2021-09-02 14:16
> #783 there is a PR with a fix but yes the 1.6.9.0 has no Problems ^^

Where did you get a previous version?

**Comment by yashpalgoyal1304** [comment] 2021-09-04 17:12
duplicate of the exisiting #769

**Comment by dinhtrung3997** [comment] 2021-09-05 12:54
Same issue, should back 1.6.9.0 to fix.

**Comment by XSweight** [comment] 2021-09-18 21:07
having the same issue

**Comment by ChrisAnd1998** [comment] 2021-12-25 10:50
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️

**Closed by ChrisAnd1998** 2021-12-25 10:50 UTC
