### ISSUE TITLE
Show desktop can't be clicked on the extreme bottom-right pixel

### ISSUE THREAD

**Issue by Falki-git** [ChrisAnd1998/TaskbarX#717] opened 2021-07-03 10:19 UTC
**Describe the bug**
When you move your mouse to the very bottom-right corner (last pixel) show desktop button can't be clicked. This is very important for quickly clicking on the button as you can just flick your mouse down-right without "aiming" at the button

**To Reproduce**
1. Move your mouse completely down and right
2. Try clicking, nothing happens 
3. Move your mouse 1 pixel up or left - it now works

**Expected behavior**
The bottom-right pixel also hovers the show desktop button 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 2004

**Additional context**
Tried the latest release 1.7.0.0 as well as the pre-release 1.7.1.0 - problem persists

**Comment by moxwel** [comment] 2021-07-04 00:53
Can confirm this problem persists.

When clicking the "Show Desktop" at the very bottom pixel, it doesn't work.
![problem](https://user-images.githubusercontent.com/49621788/124370029-6c6c8100-dc40-11eb-9a8c-f373514842b0.png)

It's kind of annoying, I use that button a lot.

However, this problem doesn't happen with the Start Menu button.
![problem2](https://user-images.githubusercontent.com/49621788/124370039-8908b900-dc40-11eb-8fa7-8c6c3a76d8c3.png)

**Comment by luisconceicao1** [comment] 2021-07-04 20:56
I'm having the same issue here :/ I lost a few hours trying to solve it but didn't work. 😢 

- could you please fix it? I like so much the TaskBarX I'm missing it a lot :(

**Comment by luisconceicao1** [comment] 2021-07-04 20:56
As issue #716 it is the same as me.

**Comment by sleepnov4** [comment] 2021-07-06 01:04
Yes, this case is the same as mine. You should remove this case because this is a duplicated issue. You also can forward or send your issue to my problem case.

**Comment by sleepnov4** [comment] 2021-07-06 04:32
I did some research about your issue and this issue already got fixed. Someone already report this kind of issue (#682). Maybe you can use the **Pre-release** version **1.7.1.0**. You can download it from [here](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0).

**Comment by moxwel** [comment] 2021-07-06 04:58
> I did some research about your issue and this issue already got fixed. Someone already report this kind of issue (#682). Maybe you can use the **Pre-release** version **1.7.1.0**. You can download it from [here](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0).

@sleepnov4 The issue about the "Show Desktop" button persists on version 1.7.1.0.

**Comment by Falki-git** [comment] 2021-07-06 14:50
> I did some research about your issue and this issue already got fixed. Someone already report this kind of issue (#682). Maybe you can use the **Pre-release** version **1.7.1.0**. You can download it from [here](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0).

No, this issue isn't the same as [#682](https://github.com/ChrisAnd1998/TaskbarX/issues/682), although the root cause is probably the same.

As I stated in the description of this issue, I already tested 1.7.1.0 and the issue isn't resolved. 1.7.1.0 resolves that the task bar is moved all the way to the bottom, so you can now click taskbar items while hovering the mouse on the last bottom pixel of the item. However, this show desktop button issue is still affected for the bottom-right pixel of the show desktop button.

**Comment by gestudio** [comment] 2021-07-15 22:46
Use Windows+D, faster, does the same.

**Comment by axone13** [comment] 2021-07-19 02:30
I confirm this problem on version 1.7.1.0. I fixed that by following these steps:
1. Uninstall TaskbarX version 1.7.1.0 through TaskbarX Configurator.exe
2. Remove all the files related to TaskbarX version 1.7.1.0
3. Lock the taskbar by right-clicking on it
4. Restart the pc
5. Install TaskbarX version 1.6.9.0

I don't know if the problem was with the new version or with the unlocked taskbar. But after locking the taskbar and downgrade to version 1.6.9.0 the problem was gone.
One more thing, after disabling TaskbarX version 1.7.1.0 the problem still exist until next reboot. So at step 4 I restarted the pc to fix that.

**Comment by stiffbruno** [comment] 2021-07-22 20:54
I confirm this issue, and as stated above, the problem don't exist in version 1.6.9.0.

**Comment by Double-A-92** [comment] 2021-08-31 22:24
Can confirm that this issue is still present in version 1.7.2.0. 

The bottom right pixel is even _visually_ missing from the taskbar. 

In general it seems like the bottom-right most pixel of the whole _screen_ is not active. E.g. this issue also happens if you have a vertical task bar on the right side of your screen.

**Comment by Falki-git** [comment] 2021-09-05 19:30
Issue still persists in 1.7.2.0

**Comment by ChrisAnd1998** [comment] 2021-12-25 10:57
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️

**Comment by Double-A-92** [comment] 2021-12-25 17:47
This still happens in the newest version (1.7.4.0). 
Is there a way to reopen this issue here, so the information in the thread doesn't get lost?

**Comment by ChrisAnd1998** [comment] 2021-12-25 18:31
I confirm this happens for me too. Now I will find out what is causing this to happen ;)

**Comment by ChrisAnd1998** [comment] 2021-12-25 18:54
Should be fixed now. 
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.5.0

**Comment by yashpalgoyal1304** [comment] 2021-12-25 19:33
* can u share the fixing commit??
* and if it's confirmed that it's fixed, then shouldnt this issue be closed?
* if the confirmation is awaited, then that should be mentioned in last comment or via a label indicating that (smth like "waiting on response/input" etc...)

**Comment by ChrisAnd1998** [comment] 2021-12-25 19:50
@yashpalgoyal1304 I have added a label "Awaiting confirmation" now. The issue will be closed when confirmed indeed. Normally i don't do commits but if you really want it i will when the issue is confirmed fixed.

**Comment by yashpalgoyal1304** [comment] 2021-12-25 20:02
awesome (:

**Closed** 2021-12-26 09:07 UTC
Labels: Added to Pre-release, Awaiting confirmation

**Comment by Double-A-92** [comment] 2021-12-26 13:36
This fixed it for me. Thanks for the quick work. :)
