### ISSUE TITLE
Icons make a big swing sometimes.

### ISSUE THREAD

**Issue by fxzxmicah** [ChrisAnd1998/TaskbarX#87] opened 2019-11-26 07:36 UTC
In some cases where I don't know the rules clearly, the icons sticked to the taskbar will swing left and right when not in use.

**Comment by harrynguyen0791** [comment] 2019-11-26 07:58
I have the same issue

**Comment by ChrisAnd1998** [comment] 2019-12-01 13:45
I have seen it happen but, i don't know why or how it happens yet.

**Comment by fxzxmicah** [comment] 2019-12-01 14:45
Well, I don't know, too. This bug is a little too magical. Sometimes it makes me dizzy.😓

**Comment by ChrisAnd1998** [comment] 2019-12-01 15:07
XD, I hope i can found out to fix it but, it happens very rarely on my side.
I will also try to detect the behavior so it will ignore the event if theres such a big position difference.

**Comment by fxzxmicah** [comment] 2019-12-01 15:33
In fact, I can see here that it is only a small left-right vibration, but it often occurs, even so, I can not find the law of its occurrence.

**Comment by ChrisAnd1998** [comment] 2019-12-01 15:45
Well the vibration issue should be fixed now. I just uploaded version 1.3.3.0.

**Comment by dkomeshak** [comment] 2019-12-03 17:38
I have version 1.3.3.0 and have this issue. I also have dual monitors and notice that the taskbar on my second monitor stops being centered when the issue is noticed.

**Comment by fxzxmicah** [comment] 2019-12-15 13:02
This issue has been fixed on my computer. Thanks. @ChrisAnd1998

**Closed** 2020-04-13 14:37 UTC
Labels: Fixed/Added in new upcomming rewrite (TaskbarX) ⏫
