### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by Kaleb-Jen-1619** [ChrisAnd1998/TaskbarX#167] opened 2020-02-08 23:23 UTC
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at FalconX4.Gui.Button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
FalconXSettings
    Assembly Version: 1.3.9.0
    Win32 Version: 1.3.9.0
    CodeBase: file:///C:/Users/{redacted}/Downloads/FalconX_19.01.2020_1.3.9.0/FalconXSettings.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ChrisAnd1998** [comment] 2020-02-09 08:17
Well i think it got removed by your antivirus software.

**Comment by NicoASMB** [comment] 2020-02-14 21:30
I'm having the exact same issue and it happens every time I try to save a setting. My only antivirus software is Windows Defender and after closing the window showing the error, the clock and tray on my taskbar is gone. I have to restart explorer.exe in order to get them back.

**Comment by Cortog** [comment] 2020-02-19 11:54
Just chiming in to say I have the same issue, also have to restart explorer. Also only Windows Defender.
I do have QTtabbar and Fences installed. But switching them off doesn't help.

**Comment by ChrisAnd1998** [comment] 2020-02-19 16:06
@Cortog @NicoASMB @Kaleb-Jen-1619 Do you use the store version or just the regular one? 

If it's the store version then there could be permission issues i don't know of. Or a bug that has issues saving the settings in 1.4.0.0 and lower which i fixed in 1.4.1.0.

**Comment by NicoASMB** [comment] 2020-02-19 16:20
@ChrisAnd1998 

I'm using the regular version.

**Comment by Cortog** [comment] 2020-02-20 13:46
@ChrisAnd1998 I'm also using the regular version but I am running 1.4.1.0 . The fault code first only appeared on my laptop, but today it also started showing up on my desktop. I updated Windows 10 to 1909 yesterday evening so that might have something to do with it.

**Comment by ChrisAnd1998** [comment] 2020-02-20 16:19
Weird :/ 
It's working fine on my laptop with Windows 10 1909 x64
My main pc is running Windows 10 2004 x64 (insider preview) which also runs fine...

**Comment by NicoASMB** [comment] 2020-02-21 16:29
@ChrisAnd1998 

I've just updated to 1.4.1.0 (regular version) and the error is gone for me.
I'm on Windows 10 1909 (Build 18363.657) x64

**Comment by Cortog** [comment] 2020-02-21 16:38
For me it seems to only appear if I click the restart or save button in the settings exe. So when starting falconx.exe it is fine. The workaround for me is to change settings -> save -> crash -> run falconx.exe. 

I have only confirmed this to work on my laptop since I don't currently have access to my desktop. 

Both are running Microsoft accounts btw, I don't know if that makes any difference to do with file access?

**Comment by NicoASMB** [comment] 2020-02-22 17:49
And the error is back with Version 1.4.2.0. Whenever I try to save something, I'll get the original error message.

**Comment by Cortog** [comment] 2020-02-22 18:22
The error is gone for me on my laptop, on 1.4.1.0 and 1.4.2.0 alike....
This is really strange.

**Comment by ChrisAnd1998** [comment] 2020-02-22 18:26
I have no clue 😔. 1.4.2.0 was just a quick fix for an error message i needed to show when debugging. I forgot to take it out in 1.4.1.0. 1.4.2.0 just ignores that message. So there isn't a difference between 1.4.1.0 and 1.4.2.0

**Comment by ChrisAnd1998** [comment] 2020-04-14 16:36
Still happening in TaskbarX 1.5.1.0 ?

**Comment by NicoASMB** [comment] 2020-04-14 16:44
@ChrisAnd1998 

Seems to be working fine so far. Thank you!

**Comment by ChrisAnd1998** [comment] 2020-04-14 16:48
@NicoASMB Great! also thank you for the quick reply!

**Closed by ChrisAnd1998** 2020-04-14 16:48 UTC
Labels: Might be a bug not found a way to reproduce ⚠️
