### ISSUE TITLE
Dynamic Taskbar options

### ISSUE THREAD

**Issue by kj3moraes** [ChrisAnd1998/TaskbarX#765] opened 2021-08-05 17:25 UTC
This feature request is not related to any problem, rather it is an idea to alter its behaviour slightly.

I suggest having more options for the 'Switch back to ______ on maximized window'. Preferably, like a dropdown that allows you to choose a different style when a window is maximized. So if the default is Style #i, the dropdown would allow you to choose Style #j (could also add an option to keep the styles the same for both).

Solus Budgie 4.3 does this very well. You can alternate the styles of the taskbar for maximized windows and otherwise.

**Comment by yashpalgoyal1304** [comment] 2021-09-04 18:46
related issue: #772 

i thought about #772 as well, but that seems way too tricky. if that's so, then i'd say that that issue can be closed as out of scope or duplicate of this one.

**Comment by ChrisAnd1998** [comment] 2021-12-25 10:53
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️

**Closed by ChrisAnd1998** 2021-12-25 10:53 UTC
