### ISSUE TITLE
as I work: open close programs, the icons creep towards the right.

### ISSUE THREAD

**Issue by cmputerboom** [ChrisAnd1998/TaskbarX#269] opened 2020-05-04 13:53 UTC
as I work and I open close programs, the icons instead of being centered on my screen, they creep towards the right and eventually they start getting hidden by the clock. Then t I have stop and start taskbarx for them to be "recentered"

**Comment by s-frei** [comment] 2020-05-06 20:09
Same here

**Comment by liyafe1997** [comment] 2020-06-05 10:22
Me too. I found it is easier to reproduce when connect to a externel monitor. My main monitor is 1920x1080 and 2nd monitor is 1024x768.

**Comment by liyafe1997** [comment] 2020-06-08 11:56
@ChrisAnd1998 I found a way to reproduce:

It cause by tray icons (Include language icon), if you modify tray icon(like a icon appear and disappear) too fast (changed before animate finished), it will cause all the taskbar icon always creep to the right. The only way to deal with it is restart TaskbarX.

![11111](https://user-images.githubusercontent.com/18359157/84027604-d1b05d00-a9c1-11ea-9698-cb04dbc3456f.gif)

**Comment by ChrisAnd1998** [comment] 2020-06-08 12:43
@liyafe1997 I can't reproduce it but, i think having the internet speed toolbar and those 2 icons there on the left might be causing this issue.

**Comment by liyafe1997** [comment] 2020-06-08 12:58
> @liyafe1997 I can't reproduce it but, i think having the internet speed toolbar and those 2 icons there on the left might be causing this issue.

YES I found. if you have toolbar in the left side it can 100% reproduce.

**Comment by liyafe1997** [comment] 2020-06-08 13:01
And it have no problem in previous version, I can't remember from which version. But I can sure it have no problem before 2020 January 1st.

**Comment by Sidneys1** [comment] 2020-08-26 12:49
I have a toolbar on the left, and this happens to me consistently. I've had to stop using TaskbarX.

**Comment by ericpa06** [comment] 2020-10-16 12:11
I just came here to reinforce that this bug still exists. It happens exactly as the AliffanI gif shows, usually when you're open and closing a program, especially if you open and close programs very fast in a brief period of time. As far as I remember, this bug always appeared on all taskbarX versions.

**Comment by ericpa06** [comment] 2020-10-18 06:38
For those trying to find a solution for this issue, I think that if you disable animation transitions, there is **"Animation Style"** and **"Animation Style on Battery"**, as well as increasing the refresh rate to 1000, this seems to somewhat solve the issue. My impression is that it's probably related to TaskbarX getting confused when you open and close a program very fast and instead of waiting and just ignoring those opened and closed icons on the taskbar, it sorta freaks out and presents this behavior.

**Comment by ChrisAnd1998** [comment] 2020-10-18 07:04
The 1.6.3.0 pre-release can be tested. I'm slowly working on fixing issues with toolbars next to the start button which also could cause the issue. It may not work already but, i made some changes.

**Comment by ericpa06** [comment] 2020-10-18 15:44
Thank you very much, I will give a look into. Also, thank you for creating this software, it's pretty goddammit good and provides a really useful, if not essential, feature I believe.

**Comment by ericpa06** [comment] 2020-10-18 19:20
Hi, I just wanted to inform you that the bug still seems to be present on the newer version. The context in which the bug appears it's still the same: you successively close and open a given window too fast, it eventually triggers the bug. If you're having any issue on reproducing the problem, I found out that if you have some lightweight program, the kind you can open and close really really fast, and if you have some key binding to open and close that program, it's very easy to trigger: just pressed that key binding successively very fast.

I was able to trigger the bug by using the software "Everything Voidtools" search program and the key binding F3, that opens a new search window, just pressing rapidly it will trigger the bug

**Comment by ChrisAnd1998** [comment] 2020-12-06 09:03
@ericpa06 I have been trying this for a while but, sadly i can't reproduce it. I also tried it with the run box WIN+R.

**Comment by ericpa06** [comment] 2020-12-06 14:50
No problem, ChrisAnd1998, thank you for your time and consideration :) By the few replies here this issue seems to affect few people, and it could maybe be boil down to a peculiar set of hardware, or some unusual software running in the background, maybe some peculiar workflow that occasionally trigger this as well.

Anyway, for those who might be affected by this I found out that the issue seems to not happen in older versions of the program, I've been using the 1.2.0.0 version and this practically never happen, so if anyone cross with this, this could be useful.

**Comment by AliffanI** [comment] 2021-01-10 15:35
Hey all, I've just updated TaskbarX via Microsoft Store to 1.6.4.0. It looks like the issue is now resolved on my end! Taskbar icons don't jump to the right if new tray icons appear anymore. Maybe some of you can confirm on your machines.

![ezgif-1-14f20e1c214c](https://user-images.githubusercontent.com/14256409/104127286-e3ad1080-5393-11eb-85b0-2891aed91835.gif)

**Closed** 2021-03-21 10:29 UTC
Labels: Issue Priority: Normal, Unable to reproduce
