### ISSUE TITLE
Unable to use TaskbarX

### ISSUE THREAD

**Issue by japkov** [ChrisAnd1998/TaskbarX#363] opened 2020-08-15 19:27 UTC
Program doesn't seem to be launching at all (either with current user or via Administrator elevation) - can't see it in Task Manager; TaskbarX Configurator does open but doesn't apply any settings. What's surprising, the FalconX 16.11.2019 - 1.3.2.0 works without issues.

I'm on Windows 10 x64 PLK build 2004 (19041.450) but the issue was present on Windows 10 build 1903 from which I've upgraded.

**Comment by ChrisAnd1998** [comment] 2020-08-16 06:12
@japkov I don't have an idea why it wouldn't even launch as it should be working on any build of windows 10.
Maybe an Antivirus flagging TaskbarX?
If not can you try this?
And follow the "How can i debug?" section.
Maybe this will indicate where the issue is...
https://github.com/ChrisAnd1998/TaskbarX/issues/274

**Comment by japkov** [comment] 2020-08-16 08:03
I have no idea what happened but it run normally - both TaskbarX and Configurator. I did tested this twice launching program yesterday (and thousand times in build 1903) with Administrator elevation but then it didn't worked and now it does - without any output in dnSpy.

![image](https://user-images.githubusercontent.com/69731550/90329707-67aaca00-dfa7-11ea-8d6e-e33c94401a10.png)

![image](https://user-images.githubusercontent.com/69731550/90329713-6da0ab00-dfa7-11ea-98a1-9578fcbb7072.png)

I'll test it for few days and give any comment if something happen.

**Comment by ChrisAnd1998** [comment] 2020-08-16 11:34
@japkov Ohh well... didn't expect that XD.

**Comment by eltoncezar** [comment] 2020-08-18 13:50
Could be related to some Windows updates. Mine was working fine as always, and then, after an forced update from my employer, it stopped, along with 7+ Taskbar Tweaker.

**Comment by japkov** [comment] 2020-08-20 08:42
I still have no clue what exacltly happened in my case; could be some .NET components missing or overall compatibility of this particular language version of W10.

Program lauches itself and the scheduled task works without issues (tho, I had to add highest rights or whatever this is called in English version) but I've noticed that sometimes centering bugs out while switching between virtual desktops:

![image](https://user-images.githubusercontent.com/69731550/90747780-a3100600-e2d1-11ea-9f8b-758545c69e95.png)

![image](https://user-images.githubusercontent.com/69731550/90747822-adca9b00-e2d1-11ea-9b54-674b9308d3a9.png)

It remains in that wa until one of programs (no way to determine visually) is closed then it snaps back as it should be - in the center

**Comment by ChrisAnd1998** [comment] 2020-08-20 09:16
No idea what could have been the issue. I think if you update to 1.5.7.0 the misplacement of the icons will be fixed.

**Comment by japkov** [comment] 2020-08-24 08:01
I've updated, tested - it seems it's fine now so I think we can close this. Thanks!

**Closed** 2020-08-25 14:00 UTC
Labels: Finding the issue 🧐
